version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - RUBY_VERSION=3.4.3
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
      - node_modules:/rails/node_modules
    environment:
      - RAILS_ENV=development
      - BUNDLE_WITHOUT=
      - BUNDLE_DEPLOYMENT=0
      - RAILS_LOG_TO_STDOUT=true
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails server -b 0.0.0.0"

volumes:
  bundle_cache:
  node_modules:
