version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - sqlite_data:/rails/storage
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
      # You'll need to set this in a real environment
      - SECRET_KEY_BASE=temporary_key_for_development
    command: ./bin/rails server -b 0.0.0.0

volumes:
  sqlite_data: